apiVersion: v1
kind: Pod
metadata:
  name: busybox-echo
  namespace: p-farrukh
spec:
  containers:
    - name: busybox
      image: busybox
      command: ["sh", "-c", "echo 'hello world' && exit 0"]
  restartPolicy: Never
