apiVersion: v1
kind: Pod
metadata:
  namespace: p-farrukh
  name: redis-pod-1
  namespace: p-farrukh
  labels:
    app: redis
spec:
  containers:
    - name: redis
      image: redis
      ports:
        - containerPort: 6379
      readinessProbe:
        tcpSocket:
          port: 6379
        initialDelaySeconds: 5
        periodSeconds: 10
  nodeSelector:
    redis: "true"
---
apiVersion: v1
kind: Pod
metadata:
  name: redis-pod-2
  namespace: p-farrukh
  labels:
    app: redis
spec:
  containers:
    - name: redis
      image: redis
      ports:
        - containerPort: 6379
      readinessProbe:
        tcpSocket:
          port: 6379
        initialDelaySeconds: 5
        periodSeconds: 10
  nodeSelector:
    redis: "true"

