apiVersion: v1
kind: Pod
metadata:
  name: test-pod
  namespace: p-farrukh
spec:
  serviceAccountName: my-sa
  containers:
  - name: test-container
    image: bitnami/kubectl
    command: ["sleep", "3600"]
