apiVersion: apps/v1
kind: Deployment
metadata:
  name: something-app
  namespace: p-farrukh
spec:
  replicas: 1
  selector:
    matchLabels:
      app: something-app
  template:
    metadata:
      labels:
        app: something-app
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/hostname
                    operator: In
                    values:
                      - node1
      containers:
        - name: something-container
          image: nvrbckdown/something:latest
          ports:
            - containerPort: 80
          livenessProbe:
            tcpSocket:
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 10
